### ISSUE TITLE
Error in the presence of destructuring block args (and constant?)

### ISSUE THREAD

**Issue by owst** [owst/rbar#1]
Given:
```
CONST = 123

{
}.each do |(a, b, c, d), expected|
  x = a ? 1 : 2

  Foo.new(x: x, y: 10)
end
```
trying to  inline `x` fails with
```
/home/owen/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rbar-0.2.0/lib/rbar/inline.rb:126:in `same_name?': undefined method `name' for #<Parser::Source::Map::Collection:0x007fd0f9123f28> (NoMethodError)
	from /home/owen/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rbar-0.2.0/lib/rbar/inline.rb:122:in `block in binds_same_arg?'
	from /home/owen/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rbar-0.2.0/lib/rbar/inline.rb:122:in `any?'
	from /home/owen/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rbar-0.2.0/lib/rbar/inline.rb:122:in `binds_same_arg?'
	from /home/owen/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rbar-0.2.0/lib/rbar/inline.rb:102:in `on_block'
	from /home/owen/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/ast-2.3.0/lib/ast/processor/mixin.rb:259:in `process'
	from /home/owen/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rbar-0.2.0/lib/rbar/inline.rb:31:in `block in on_begin'
	from /home/owen/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rbar-0.2.0/lib/rbar/inline.rb:25:in `each'
	from /home/owen/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rbar-0.2.0/lib/rbar/inline.rb:25:in `on_begin'
	from /home/owen/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/ast-2.3.0/lib/ast/processor/mixin.rb:259:in `process'
	from /home/owen/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rbar-0.2.0/lib/rbar/inline.rb:5:in `rewrite'
	from /home/owen/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rbar-0.2.0/lib/rbar/cli.rb:21:in `inline'
	from /home/owen/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /home/owen/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/owen/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /home/owen/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /home/owen/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rbar-0.2.0/exe/rbar:4:in `<top (required)>'
	from /home/owen/.rbenv/versions/2.3.3/bin/rbar:22:in `load'
	from /home/owen/.rbenv/versions/2.3.3/bin/rbar:22:in `<main>'

```
strangely, either deleting `CONST` or making `(a, b, c, d)` just `a, b, c, d` avoids the problem.

**Comment by owst** [comment]
Fixed by #2
